### PR TITLE
Release 0.3.3

### PR DESCRIPTION
**Pull request by ax3l**
Alpaka 0.3.3 release.

All backports applied:
- [x] see PR #588 
- [x] see VS fix in #598 
- [x] Travis: fix clang 6.0 download URL

### CODE REVIEW

**Comment by ax3l** [comment]
@BenjaminW3 shall we release 0.3.3? :-)

**Comment by ax3l** [comment]
@BenjaminW3 ping :)

**Comment by BenjaminW3** [comment]
I will create the release notes.

**Comment by sbastrakov** [comment]
Just a side note: some alpaka release notes e.g., the 0.3.1 and the new 0.3.3, are seemingly randomly mixing the present and past tenses in lists of bugs fixes or features added. 0.3.2 and 0.3.0 use only the past.

**Comment by BenjaminW3** [comment]
Fixed

**Comment by ax3l** [comment]
Fixes the GitHub release notes as well and added the DOI tag.
Weirdly, I can't edit the Zenodo anymore...

**Pull request merged**
