### PR TITLE
merge develop to master to prepare release

### PR DESCRIPTION
**Pull request by BenjaminW3**
This will get the next stable version. It seems to be reasonably stable and has a broad support for compilers and toolchains.
However, after this release older CUDA/gcc/clang/MSVC/boost versions will be dropped. This will allow us to decrease the test matrix to get faster results and to remove workarounds for older compilers and toolchains. Furthermore, this will hopefully allow us to use newer C++/CUDA features.

Wait for:
* [x] #465

### CODE REVIEW

**Comment by BenjaminW3** [comment]
I can wait a few days with the release for this feature ;-)

**Comment by ax3l** [comment]
turns out I am on vacation for the next week, so it will take indeed a week before I can work on this again.

**Comment by ax3l** [comment]
@BenjaminW3 anyway, go ahead with this. we can fix the install in the next release

**Comment by psychocoderHPC** [comment]
@benjamin can I merge this PR?

**Comment by BenjaminW3** [comment]
merged ;-)

**Comment by BenjaminW3** [comment]
released ;-)

**Pull request merged**
