### PR TITLE
remove all trailing whitespaces

### PR DESCRIPTION
**Pull request by BenjaminW3**

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Did you run a tool over the code to remove the white spaces?
If not [this](https://github.com/ComputationalRadiationPhysics/picongpu/pull/520) pull in PIConGPU shows how it can performed one the hole code.

Could you commit this changes by an pseudo author ( e.g.Tools )? 

```
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="alpaka@hzdr.de" git commit ...
```

**Comment by BenjaminW3** [comment]
Yes I have used a tool.
The author is now "Tools <tools@alpaka.com>"

**Comment by psychocoderHPC** [comment]
Is "Tools tools@alpaka.com" the name or the author? 
Could you please change "@alpaka.com" to a domain which we own.

**Comment by BenjaminW3** [comment]
It is the notation used to specify both within a single git commit line, e.g.: `git commit --amend --author "Author Name <email@address.com>"`
If @alpaka.com is not good I would prefer @example.com because it is reserved and will never get registered even if hzdr.de will get unregistered in the unforseeable future.

**Comment by psychocoderHPC** [comment]
I am fine with @example.com

**Comment by BenjaminW3** [comment]
Updated!

**Pull request merged**
