### PR TITLE
use Weverything for clang

### PR DESCRIPTION
**Pull request by BenjaminW3**
This enables `-Weverything` for clang which includes `-Wall` and all other warnings that clang can provide (only within CI builds).
Most warnings have been fixed (member order for better packing, explicit casts, invalid documentation) or disabled locally.
Only 3 warnings had to be disabled globally.
Furthermore, warnings within boost had to be silenced.

### CODE REVIEW

**Comment by bussmann** [comment]
Yeah!

**Comment by BenjaminW3** [comment]
Ready!

**Comment by psychocoderHPC** [comment]
I review it next week.

**Comment by psychocoderHPC** [comment]
thanks for removing all the implicit cast and adding more comments!

**Pull request merged**
