### PR TITLE
remove boost.context from ReadMe requirements

### PR DESCRIPTION
**Pull request by BenjaminW3**

### CODE REVIEW

**Comment by ax3l** [comment]
oh, good to know. I just added that to PIConGPU ;)

Is context not a requirement of fibers anymore?

**Comment by ax3l** [comment]
oh, good to know. I just added that to PIConGPU ;)

Is context not a requirement of fiber anymore?

**Comment by ax3l** [comment]
@BenjaminW3 also, the `alpakaConfig.cmake` still seems to require a good ammount of components that need compiles: `FIND_PACKAGE(fiber context system thread atomic chrono date_time)`

**Comment by BenjaminW3** [comment]
Yes, all of those are dependencies of boost fiber. However, I only mentioned one transitive dependeny boost context and not the others. This was inconsistent. So I preferred to remove this one. The dependencies of fiber could change with every boost version. So I do not want to mention them explicitly. Boost build should handle to build those dependencies automatically.

**Comment by ax3l** [comment]
Ok that's fine. Unluckily CMake is always behind keeping the transitive deps up-to-date until they fully switch to CMake in the future, so we did mention transitive deps (e.g. system in filesystem) explicitly so far.

Nevertheless, what is the correct way to import alpaka via cupla with its pulled dependencies. It looks to me that a found boost fiber third-party dependency is not fully forwarded to PIConGPU yet.

**Comment by ax3l** [comment]
Ah I think I found the cause. `PMaccConfig.cmake` does not yet forward the cupla libs...

**Pull request merged**
