### PR TITLE
Backports for 0.3.4 Part 2

### PR DESCRIPTION
**Pull request by ax3l**
Contains the following backports:

- Add a check for OpenMP version #630
- Added prepareForAsyncCopy trait and specialization for cpu and cuda memory #633
- Glibc < 2.18: Fix Missing Macros #624
- CUDA: Math & Public Headers #650
- Fix static_casts leading to overflows. #646
- Fix tests using std::int16_t overflowing #648 
- Mem Tests: Boost Predef #670 (just validated it did not creep in)
- Check definition of `__GLIBCXX__` first #672
- AppVeyor: Update with same logic as in `dev` (Boost 1.66.0)

### CODE REVIEW

**Comment by ax3l** [comment]
I see an
```
include/alpaka/atomic/AtomicCudaBuiltIn.hpp(108) Error: unsupported operation

CMake Error at atomic_generated_AtomicTest.cpp.o.cmake:279 (message):
  Error generating file
  /home/huebl/src/alpaka/build/test/unit/atomic/CMakeFiles/atomic.dir/src/./atomic_generated_AtomicTest.cpp.o
```

when building the tests with NVCC 8.0.44 but I am not sure they build anyway in the 0.3.X release branch?

**Comment by BenjaminW3** [comment]
The current 0.3.4 release build has been successful (not for windows): https://travis-ci.org/ComputationalRadiationPhysics/alpaka/builds/433959268 . So the error should be new.

**Comment by ax3l** [comment]
Travis CI passes as usual. Any idea what AppVeyor is sad about? :)

**Comment by BenjaminW3** [comment]
It is complaining about OOM `c:\projects\alpaka\test\unit\kernel\src\kernellambda.cpp(216): fatal error C1060: compiler is out of heap space`. I have fixed this by splitting some tests (this one) and excluding others for Appveyor.

**Pull request merged**
