### PR TITLE
add TBB to the windows CI tests

### PR DESCRIPTION
**Pull request by BenjaminW3**
Appveyor has changed its build farm and the build times have been reduced to 1/4. This allows us to extend the tests.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
When the ReadMe change regarding TBB is reverted, the question mark for Windows will have to be replaced with a check-mark.

**Comment by psychocoderHPC** [comment]
I  can't follow you. Where is a question mark for Windows?

**Comment by BenjaminW3** [comment]
In #260 the TBB line in the Readme had been removed which contained :grey_question: for Windows. When this is reverted, it should be replace by a :white_check_mark: now.

**Comment by psychocoderHPC** [comment]
ok thanks I hope I can keep it in my mind^^

**Pull request merged**
