### PR TITLE
remove support for CUDA 7.x

### PR DESCRIPTION
**Pull request by BenjaminW3**
This adds unconditional support for device lambdas (7.5) and heterogeneous lambdas (8.0).
Furthermore, this allows to move the `EventHostManualTrigger` (8.0) out of the test code to make it publicly available in a follow up Pull Request.

### CODE REVIEW

**Comment by ax3l** [comment]
Hm, 7.5 as well? This will drop [Titan](https://www.olcf.ornl.gov/olcf-resources/compute-systems/titan/)...

**Comment by BenjaminW3** [comment]
CUDA 8.0 was released in Sept 2016.
We still have the last release available which supports 7.0/7.5.
Which CUDA versions do other projects support at the moment? (PIConGPU, ISAAC, thrust, ...)?

**Comment by ax3l** [comment]
PIConGPU technically supports CUDA 7.5 if we replace our currently very long MPL lists with something else (mp11). https://github.com/ComputationalRadiationPhysics/picongpu/pull/2408

But if mp11 migration takes longer we will probably have to drop CUDA 7.5 for it as well...

ISAAC is CUDA 7.0+.

Thrust is shipped patched in CUDA itself.

**Comment by ax3l** [comment]
> CUDA 8.0 was released in Sept 2016.

Yeah, I know. Titan went online in 2013 and got several major CUDA updates (5.X to 7.5) but since Summit is the near leadership system it looks like it stays with CUDA 7.5...

**Comment by ax3l** [comment]
If you like: I have a little time to push some installer updates these days and we can make another release that supports CUDA 7.0/7.5 with a `make install` / `cmake --build . --target INSTALL --config Release` these days.

**Comment by ax3l** [comment]
Feel free to rebase and go ahead, we will do a `0.3.1` bugfix release for PIConGPU 0.4.0

**Comment by ax3l** [comment]
Hurray, CUDA 9 is coming to Titan as well!
https://www.olcf.ornl.gov/center-announcement/weekly-update-06jun2018/

**Pull request merged**
