### PR TITLE
Move ViewStdContainers into seperate headers

### PR DESCRIPTION
**Pull request by BenjaminW3**
There is no real change in those files. The one file has simply been split into three files. Even the commented out parts are still commented out.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Ready for review ;-)

**Comment by ax3l** [comment]
@sbastrakov @theZiz @tdd11235813 ping

**Comment by BenjaminW3** [comment]
Do we really want to have "Require review from Code Owners" enabled? This currently hinders me from merging this branch, because the reviewer is not "privileged" enough.

**Comment by ax3l** [comment]
(Or should we give @theZiz more responsibilities for alpaka?)

**Pull request merged**
