### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by BenjaminW3**
As there are no open tickets for version 0.1.0, develop should be merged to master to prepare the release.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Thanks for preparing this pull request. I need some additional information from @ax3l how to create a doi and than we can release this branch.

**Comment by erikzenker** [comment]
Release :sparkles:

**Comment by psychocoderHPC** [comment]
Is the zenodo DOI now created?

**Comment by ax3l** [comment]
not yet, we two can do this today or tomorrow (we will create both a tag and then the DOI for it)

**Pull request merged**
