### PR TITLE
reduce the CI compilation times

### PR DESCRIPTION
**Pull request by BenjaminW3**
This Pull Request reduces the compilation times (issue #192).
The atomic operations unit test increased the gcc and MSVC compilation times dramatically. However, clang was not affected that much.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
The AppVeyor build times have been reduced by 15 minutes for each of the 3 jobs.

**Comment by psychocoderHPC** [comment]
what does it mean in time?

**Comment by BenjaminW3** [comment]
**AppVeyor:** old: no valid reference new: 2h.
**Travis:** old: 5 hrs 27 min 54 sec new: 2 hrs 30 min 57 sec

**Comment by BenjaminW3** [comment]
push

**Pull request merged**
