### PR TITLE
Fixed ALPAKA_FN_ACC for alpaka::math Cuda traits

### PR DESCRIPTION
**Pull request by tu-maurice**
Should solve issue #139.

### CODE REVIEW

**Comment by tu-maurice** [comment]
The CI seems to have problems downloading cmake :confused:

**Comment by BenjaminW3** [comment]
The CMake website seems to be down. However, as the changes are minimal I will merge it.

**Comment by BenjaminW3** [comment]
Please do the Pull Request against `develop` the next time.

**Comment by tu-maurice** [comment]
Oh damn. i though i did O.o sorry

**Pull request merged**
