### PR TITLE
fix test analysis

### LINKED ISSUE #364: Test Build Error: headerCheck when ALPAKA_ACC_GPU_CUDA_ENABLE == ON
Running a cmake and make directly into the root of a freshly cloned alpaka branch as of af6ebb47ebae5633f1caf5d6765e1fc5cb14ecf3 (`develop`)
```bash
cmake ~/src/alpaka/ -DCMAKE_INSTALL_PREFIX=$HOME/lib/alpaka
make
```

fails in
```
Scanning dependencies of target alpaka
[  0%] Building CXX object example/bufferCopy/CMakeFiles/alpaka.dir/__/__/include/alpaka/core/Dummy.cpp.o
[  0%] Linking CXX static library libalpaka.a
[  0%] Built target alpaka
[  0%] Building NVCC (Device) object example/bufferCopy/CMakeFiles/bufferCopy.dir/src/bufferCopy_generated_bufferCopy.cpp.o
Scanning dependencies of target bufferCopy
[  1%] Linking CXX executable bufferCopy
[  1%] Built target bufferCopy
[  1%] Building NVCC (Device) object example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld_generated_helloWorld.cpp.o
Scanning dependencies of target helloWorld
[  2%] Linking CXX executable helloWorld
[  2%] Built target helloWorld
[  2%] Building NVCC (Device) object example/helloWorldLambda/CMakeFiles/helloWorldLambda.dir/src/helloWorldLambda_generated_helloWorldLambda.cpp.o
Scanning dependencies of target helloWorldLambda
[  3%] Linking CXX executable helloWorldLambda
[  3%] Built target helloWorldLambda
[  3%] Building NVCC (Device) object example/vectorAdd/CMakeFiles/vectorAdd.dir/src/vectorAdd_generated_main.cpp.o
Scanning dependencies of target vectorAdd
[  4%] Linking CXX executable vectorAdd
[  4%] Built target vectorAdd
Scanning dependencies of target common
[  4%] Building CXX object test/analysis/headerCheck/CMakeFiles/common.dir/__/__/common/src/Dummy.cpp.o
[  5%] Linking CXX static library libcommon.a
[  5%] Built target common
make[2]: *** No rule to make target `test/analysis/headerCheck/CMakeFiles/headerCheck.dir/src/headerCheck_generated_main.cpp.o.cmake', needed by `test/analysis/headerCheck/CMakeFiles/headerCheck.dir/src/headerCheck_generated_main.cpp.o'.  Stop.
make[1]: *** [test/analysis/headerCheck/CMakeFiles/headerCheck.dir/all] Error 2
make: *** [all] Error 2
```

### System

Hypnos (HZDR)

### Software

gcc/4.9.2
boost/1.62.0
cmake/3.7.2
cuda/8.0

without: TBB, Boost.Fiber, Boost.Context

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Source Files where added two times into the source files list.
This results into a CMake error:

```
CMake Error: Files to be generated by multiple different commands: "/bigdata/hplsim/scratch/widera/alpaka/build/CMakeFiles/headerCheck.dir/src/acc/headerCheck_generated_AccCpuFibers.hpp.cpp.o.cmake"
```

- add explicit the test case main file to the list of source files
- add missing includes for CUDA backend files to pass the test
- change used CUDA version for the analysis test from CUDA 9.1 to CUDA 8.0 (CUDA 9.1 is not supported by clang 4.0.0)

fix #364

- [x] rebase against #517

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Does this fix #364? If yes, could [the special casing in this line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/script/travis/run.sh#L77) be removed with this PR as well?

**Comment by psychocoderHPC** [comment]
Yes #364 should be fixed with this PR, I updated the test in an separate commit.

**Comment by BenjaminW3** [comment]
It seems to work now!
There are still some errors:
There still seems to be missing an include in `alpaka/idx/bt/IdxBtCudaBuiltIn.hpp`.
```C++
/home/travis/build/ComputationalRadiationPhysics/alpaka/include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp(98): error: identifier "origin" is undefined
/home/travis/build/ComputationalRadiationPhysics/alpaka/include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp(98): error: too few arguments for class template "alpaka::idx::traits::GetIdx"
```
The clang build is failing and we might need to change the `.travis.yml` file to get rid of the error:
```
clang-4.0: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
```
It seems to use a default architecture of sm_20 which is not available with CUDA 9.1.
However, it I read the `alpakaConfig.cmake` correctly, this should not be the case.

**Comment by psychocoderHPC** [comment]
I pushed an update with some debug output in the CMake to find out why clang is using `sm_20` is should be avoided by https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/alpakaConfig.cmake#L321-L325

**Pull request merged**
