### PR TITLE
remove cpu::getDev()

### LINKED ISSUE #105: Remove cpu::dev and replace by getDevByIdx()
See discussion in #104

### PR DESCRIPTION
**Pull request by BenjaminW3**
This closes #105.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Correctly compiles now ;-)

**Comment by erikzenker** [comment]
Well done, I would merge this PR. But just one thing ...is there a special reasion why there is DevManCpu used instead of DevMan<Host> ?

**Comment by BenjaminW3** [comment]
There is a device manager for each device type. So there is one for CPU devices and one for GPU devices. The CPU device manager currently has only one single device.
We could also have defined a `DevHost` as `DevCpu` and then retrieved the device manager of the CPU device by calling `DevMan<DevHost>` as you have done in your examples but I think this detour is not always necessary.

**Comment by erikzenker** [comment]
I just want to mention that when `DevMan<DevCpu>` is equal to `DevManCpu` than a user could wonder which one to use.

**Pull request merged**
