### PR TITLE
use optimal heap allocation alignment

### PR DESCRIPTION
**Pull request by BenjaminW3**
First try to solve #321

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Ohh I don_t know that boost had some magic defines for the SIMD length. 
Is the define `BOOST_HW_SIMD_X86` set on user program compile time or on boost compile time. 

If it works we need to test if we can see any speed improve with matmul or vector add. (HINT: we need to compile  with `-march=native and -tune=native`)

**Comment by BenjaminW3** [comment]
Compilers define different macros e.g. `__AVX2__` depending on the target architecture. Boost.Predef only checks for the existance of the macros and defines its own macros which are much more consistent.
I will fix the clang warning in the next few days and will try to use the new alpaka version with the vecadd and matmul libs to perform some tests.

**Comment by BenjaminW3** [comment]
I have remove the usage of Boost.Predef for now because it does not yet detect AVX512 but only the MIC instruction set.

**Comment by psychocoderHPC** [comment]
Are the clang warnings fixed?

**Comment by BenjaminW3** [comment]
Everything compiles now without warnings and the tests are green. However, I had no time to test if this has any positive performance impact until now and can not etimate if I will have time to do so in the near future.

**Comment by psychocoderHPC** [comment]
@theZiz  tested the new alignments on a Intel KNL with single precision [the gemm](https://github.com/BenjaminW3/matmul) saw a speedup of `1.2` compared to the alpaka version with 16 byte alignment.

**Pull request merged**
