### PR TITLE
Fix cuda memcpy and memset for zero sized buffers (division by zero)

### PR DESCRIPTION
**Pull request by BenjaminW3**
This fixes the failing memBuf test from #537

### CODE REVIEW

**Comment by ax3l** [comment]
Maybe @psychocoderHPC can take a look tomorrow and @tdd11235813 can verify it for his bugreport :)

**Comment by psychocoderHPC** [comment]
looks good from my side but I will wait until @tdd11235813 responded before I give a :+1:

**Comment by tdd11235813** [comment]
The memBuf test works now, thanks a bunch. 
I just would like to understand the parts and to know, which cases allow the use of 0s in extents. 
I guess the zero size test case is about *"don't fail at the basics even if there are extents with zeros"*. 
Now, the enqueue for copy and (mem)set would silently return before doing anything, but it makes sense here. The ZeroSizeTest also calls the backend specific alloc function with 0 bytes, which is not well defined (it's the question if alpaka should take care of this by returning NULL pointer if size is 0).
Subsequent functions in basicBufferOperationsTest and viewTestMutable include `copy` and `verifyViewsEqual`. `copy` and `set` should not do anything and the `verifyViewsEqualKernel`/`verifyBytesSetKernel` runs with 1 Thread, but the views should be empty, so nothing happens.

**Comment by BenjaminW3** [comment]
Yes, I think you summarized everything correctly. 👍 
We skip the call to the underlying CUDA memory operation now. This should not be a problem because it would not do anything.

**Pull request merged**
