### PR TITLE
independently check the last error flag before the current error

### PR DESCRIPTION
**Pull request by BenjaminW3**
As discussed in issue #74:
Currently we are erasing the CUDA last error flag when checking for errors of CUDA functions wrapped  by the `ALPAKA_CUDA_RT_CHECK`/`ALPAKA_CUDA_RT_CHECK_IGNORE` macros. This effectively leads to the loss of all asynchronous errors of kernel calls or unwrapped CUDA calls.
By always checking for the last error before executing ad checking the current command, this can be handled gracefully.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
travis said no :-)

**Comment by BenjaminW3** [comment]
I missed a semicolon...

**Comment by BenjaminW3** [comment]
Have you tested my proposal for your specific case?

**Comment by psychocoderHPC** [comment]
It looks like the program not stops if an error is detected.
```
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/dev/DevCudaRt.hpp(523) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error: 'out of memory'!
```

**Pull request merged**
