### PR TITLE
Fix boost fiber

### PR DESCRIPTION
**Pull request by BenjaminW3**
Reenable the boost fiber compilation (#250) now that it is finally part of boost.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Very nice, is boost fiber now in the official boost release available?

**Comment by BenjaminW3** [comment]
It will be available in the boost 1.62 release.

**Comment by psychocoderHPC** [comment]
I will merge this after the release. Is it ok?

**Comment by BenjaminW3** [comment]
Yes, I want to wait until after the next boost release.

**Comment by BenjaminW3** [comment]
You can merge it after the release.

**Comment by BenjaminW3** [comment]
Boost 1.62.0 has been released and this can finally be merged!

**Comment by psychocoderHPC** [comment]
thx for readding boost fibers

**Pull request merged**
